import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ConfigProvider } from "antd";
import { WrapperApollo } from "../apollo/apollo-client";
import { AppGuard } from "../guard/appGuard";
import { SideBar } from "@/src/widgets";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-screen flex flex-col bg" suppressHydrationWarning>
        <AppGuard>
          <WrapperApollo>
            <ConfigProvider
              theme={{
                components: {
                  Menu: {
                    itemSelectedBg: "#eef0f2",
                    itemSelectedColor: "#000000",
                    itemHoverColor: "#000000",
                    itemHoverBg: "#f5f5f5",
                    itemHeight: 56,
                  },
                },
              }}
            >
              <div className="flex min-h-screen w-screen">
                <div className="w-[200px] shrink-0">
                  <SideBar />
                </div>

                <main className="flex-1 overflow-auto bg-white">
                  {children}
                </main>
              </div>
            </ConfigProvider>
          </WrapperApollo>
        </AppGuard>
      </body>
    </html>
  );
}
