import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers/Providers";

const themeInitScript = `
(function () {
  try {
    var appearance = localStorage.getItem("appearance") || "light";
    var isDark =
      appearance === "night" ||
      (appearance === "systemTheme" &&
        window.matchMedia &&
        window.matchMedia("(prefers-color-scheme: dark)").matches);

    document.documentElement.classList.toggle("dark", isDark);

    var locale = localStorage.getItem("locale");

    if (locale === "ru" || locale === "en") {
      document.documentElement.lang = locale;
    }
  } catch (error) {
    document.documentElement.classList.remove("dark");
  }
})();
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning
      >
        <head>
          <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        </head>

        <body className="min-h-screen" suppressHydrationWarning>
          <Providers>{children}</Providers>
        </body>
      </html>
  );
}